---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(forcats)
library(viridis)
library(plotly)

options(scipen = 999, digits = 4)
```

```{r}
homelessness = 
  read.csv("./data/us_homelessness_07_18.csv")

# calculating total percentage per state by year
count_total_state = 
  homelessness %>% 
  subset(state != "(Missing)") %>% 
  mutate(state = fct_explicit_na(state)) %>% 
  group_by(year, state) %>% 
  mutate(
    tot_hmls = sum(total_homeless),
    shel_hmls = sum(sheltered_homeless),
    unshel_hmls = sum(unsheltered_homeless),
    tot_hous_st = sum(total_households),
    shel_hous_st = sum(sheltered_households),
    unshel_hous_st = sum(unsheltered_households),
    tot_chr_st = sum(total_chronic),
    shel_chr_st = sum(sheltered_chronic),
    unshel_chr_st = sum(unsheltered_chronic),
    tot_vet_st = sum(total_veterans),
    shel_vet_st = sum(sheltered_veterans),
    unshel_vet_st = sum(unsheltered_veterans),
    tot_youth_st = sum(youth)
  ) %>%
  distinct(year, state, tot_hmls, shel_hmls, unshel_hmls, tot_hous_st, shel_hous_st, unshel_hous_st, tot_chr_st, shel_chr_st, unshel_chr_st, tot_vet_st, shel_vet_st, unshel_vet_st, tot_youth_st) %>% 
  mutate(
    tot_hous = round(tot_hous_st/tot_hmls, digits = 3),
    shel_hous = round(shel_hous_st/shel_hmls, digits = 3),
    unshel_hous = round(unshel_hous_st/unshel_hmls, digits = 3),
    tot_chr = round(tot_chr_st/tot_hmls, digits = 3),
    shel_chr = round(shel_chr_st/shel_hmls, digits = 3),
    unshel_chr = round(unshel_chr_st/unshel_hmls, digits = 3),
    tot_vet = round(tot_vet_st/tot_hmls, digits = 3),
    shel_vet = round(shel_vet_st/shel_hmls, digits = 3),
    unshel_vet = round(unshel_vet_st/unshel_hmls, digits = 3),
    tot_youth = round(tot_youth_st/tot_hmls, digits = 3)
  ) %>% 
  ungroup() %>% 
  select(year:unshel_hmls,tot_hous:tot_youth) %>% 
  rename(
    "Total Homeless" = tot_hmls,
    "Sheltered Homeless" = shel_hmls,
    "Unsheltered Homeless" = unshel_hmls,
    "Total Households (%)" = tot_hous,
    "Sheltered Households (%)" = shel_hous,
    "Unsheltered Households (%)" = unshel_hous,
    "Total Chronic (%)" = tot_chr,
    "Sheltered Chronic (%)" = shel_chr,
    "Unsheltered Chronic (%)" = unshel_chr,
    "Total Veterans (%)" = tot_vet,
    "Sheltered Veterans (%)" = shel_vet,
    "Unsheltereed Veterans (%)" = unshel_vet,
    "Total Youth (%)" = tot_youth
  ) %>% 
  pivot_longer("Total Homeless":"Total Youth (%)",names_to = "variable", values_to = "statistics")
## %>% pivot_wider(names_from = state, values_from = statistics)

count_total_state
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
years = 
  count_total_state %>% 
  distinct(year) %>% 
  pull()

variables = 
  count_total_state %>% 
  distinct(variable) %>% 
  pull()

# select years
selectInput(
  "year_choice",
  label = h3("Select year"),
  choices = years, selected = "2018"
  )

selectInput(
  "variable_type",
  label = h3("Select variable"),
  choices = variables, selected = "Total Homeless"
  )
```

Column {data-width=1000}
-----------------------------------------------------------------------

### Homelessness Distributions in the United States

```{r}
renderPlotly({
	geo1 <- list(
	scope = "usa",
	projection = list(type = "state"),
	showlakes = TRUE,
	lakecolor = toRGB("white")
	)
	
count_total_state %>% 
  mutate(state_name = openintro::abbr2state(state)) %>% 
	filter(variable == input[[variables]], year == input[[years]]) %>% 
	plot_geo(locationmode = "USA-states") %>% 
	add_trace(
		z = ~statistics,
		locations = ~state,
		color = ~statistics,
		colors = "Blues",
		# add text
		text = ~paste(variable, state, sep = "")
		) %>%
	layout(
		geo = geo1,
		title = "US Homelessness Distribution",
		legend = list(x = 100, y = 0.5)
	)
})
```


